#!/usr/bin/env python3.14
import json
import sys
MAX_READ_LIMIT = 100
class VMReadError(Exception): pass
class VM:
    def __init__(self):
        self.register = {}
        self.callstack = []
        self.pc = 0
        self.running = False
        self.idx = 0
        self.code = []
        self.labels = {}

        self.intructs={
        0:self.M_MATH,
            1:self.M_COMP,     2:self.M_BIN,
        3:self.M_ADDSTRING,
            4:self.L_GET,      5:self.L_CALL, 
        6:self.L_PROP,
            7:self.L_INDEX,    8:self.C_SET, 
        9:self.C_HLT,
            10:self.C_SETLABEL,11:self.F_GOTO, 
        12:self.F_CALL,
            13:self.F_RET,     14:self.F_IF,
        15:self.F_INPUT,
            16:self.F_PRINT,   17:self.F_CLEAR,
        18: self.C_INITFUNC}
    # === Machine instructions ===
    def M_MATH(self, opr, a, b, addr):
        a,b = self.convert(a,b)
        match opr:
            case '+':self.register[addr]=a+b
            case '+u':self.register[addr]=+a
            case '-':self.register[addr]=a-b
            case '*':self.register[addr]=a*b
            case '//':self.register[addr]=a//b
            case '%':self.register[addr]=a%b
            case '/': self.register[addr]=a/b
            case '**':self.register[addr]=a**b
            case '-u':self.register[addr]=-a
            case _:
                raise TypeError(f"Invalid argument {opr} must be +, -, %, / or *.")
        self.pc+=1
    def M_BIN(self, mode, a, b, addr):
        a,b=self.convert(a,b)
        becomes = None
        match mode:
         case 'or': becomes = a or b
         case 'not': becomes = not a
        self.register[addr]=becomes
        self.pc += 1
    def M_COMP(self, opr, a, b, addr):
        a,b=self.convert(a,b)
        match opr:
            case '==':self.register[addr]=a==b
            case '>=':self.register[addr]=a>=b
            case '<=':self.register[addr]=a<=b
            case '<':self.register[addr]=a<b
            case '>':self.register[addr]=a>b
            case '!=':self.register[addr]=a!=b
            case 'in':self.register[addr]=a in b
            case _:
                raise TypeError(f"Invalid argument {opr} must be ==, >=, <=, <, > or !=.")
        self.pc+=1
    def M_ADDSTRING(self, *args):
        *args, addr = args
        args = ''.join(map(self.convert,args))
        self.register[addr] += args
        self.pc += 1


    def L_GET(self, name, addr): self.register[addr] = getattr(__builtins__,name); self.pc += 1
    def L_CALL(self, fromAddr, args, toAddr=None):
        args = map(self.convert,args)
        fn = self.register.get(fromAddr)
        try:
            out = fn(*args)
            if toAddr: self.register[toAddr] = out
        except Exception as e: raise RuntimeError(f'L_CALL failed {e}')
        self.pc += 1
    def L_PROP(self, startingAddr, things, addr):
        obj = self.register.get(startingAddr)
        for v in things: obj = getattr(obj, v)
        self.register[addr] = obj
        self.pc += 1

    def convert(self, a, b=0):
        if b:
            return self.convert(a), self.convert(b)
        else:
            if type(a)==list: return self.register[a[0]]
            return a

    def L_INDEX(self, addr, index, outaddr):
        index=self.convert(index)
        self.register[outaddr] = self.register[addr][index]
        self.pc += 1
    def C_SET(self, v, addr): self.register[addr] = v; self.pc += 1
    def C_HLT(self,printregister=None):
        self.running = False
        if printregister:print("Final register:",self.register)
    def C_SETLABEL(self, label,goto=None):
        self.labels[label] = self.pc+1;self.pc = goto if goto else self.pc+1
        # if self.code[self.idx][self.pc+1][0] != 18: raise RuntimeError("Every function must start with C_INITFUNC (opc number 18)")

    def C_INITFUNC(self, *args):
        args = list(args)
        hasargs = self.callstack[-1][1]
        if not hasargs: self.pc+=1; return
        if not args: self.pc+=1; return
        for i,v in zip(map(self.convert,hasargs), args):
            self.register[v] = i
        self.callstack[-1][3] = args
        self.pc+=1

    def F_GOTO(self, addr): self.pc = addr if isinstance(addr,int) else self.labels[addr]
    def F_CALL(self, addr, args=None, returnvaladdr=None): 
        self.callstack.append([self.pc + 1,map(self.convert,args),returnvaladdr, None]); 
        newaddr = addr if isinstance(addr,int)else self.labels[addr]
        if self.code[self.idx][newaddr][0] != 18: raise RuntimeError("Every function must start with C_INITFUNC (opc number 18)")
        self.pc=newaddr
        
    def F_RET(self, returns=None):
        if not self.callstack: raise RuntimeError("callstack empty")
        pc,_,returning,delete  = self.callstack.pop()
        if returning and returns:
            self.register[returning] = self.register[returns]
            self.register.pop(returns)
        elif not(returning == None and returns == None):
            raise TypeError("Mismatch in function requests.")
        if delete: self.F_CLEAR(delete)
        self.pc = pc

    def F_IF(self, binOpAddr, addr):
        self.pc = addr if self.register.get(binOpAddr) else self.pc + 1
    def F_INPUT(self, text, addr):
        self.register[addr] = input(text)
        self.pc +=1
    def F_PRINT(self, addr):print(self.convert(addr)); self.pc +=1
    def F_CLEAR(self, sr: list | int | str, er: int=None):
        if type(sr)==list:
            for i in sr:
                print(f'deleting addr {repr(i)}, from pc {self.pc}')
                self.register.pop(i)
        elif type(sr) == int:
            if er:
                for i in range(sr,er+1):
                    print(f'deleting addr {repr(i)}, from pc {self.pc}')
                    self.register.pop(i)
            else:
                print(f'deleting addr {repr(sr)}, from pc {self.pc}')
                self.register.pop(sr)
        else:print(f'deleting addr {repr(sr)}, from pc {self.pc}'); self.register.pop(sr)
        self.pc +=1
    # === Load & run ===
    def load(self, bytecode: list):
        self.code.append(bytecode)

    def run(self,watermark=0):
        if watermark: print(f'PVM v1.5.4')
        print(', '.join([f"{i}: {self.intructs[i].__name__}" for i in self.intructs]))
        while self.idx < len(self.code):
            chunk = self.code[self.idx]
            self.pc = 0
            self.running = True
            ran = []
            lines = {}
            arp=False
            while self.running:
                try:
                    this = chunk[self.pc]
                    opc, args = this[0], this[1:]
                    ran.append([opc, args])
                    if arp: raise RecursionError(f"Reached max limit of repeating the running of line {arp}.")
                    func = self.intructs[opc]
                    func(*args)
#                    print(self.register)
                except Exception as e:
                    print(f'{type(e).__name__}: {e} @ Line {self.pc}\nErroring JSON: {chunk[self.pc]}\nregister: {self.register}\n\nRan traceback: {ran}')
                    sys.exit(1)
                else:
                    if self.pc in lines: lines[self.pc]+=1
                    else: lines[self.pc] = 0
                    if lines[self.pc] > MAX_READ_LIMIT:
                     q=input(f"Anti-repeat handler: the line {self.pc} has been read for the {lines[self.pc]}th time, continue running the code or crash? y/n ")
                     if q == 'y':
                      arp = self.pc
            self.idx += 1
if __name__ == '__main__':
    if len(sys.argv) ==1:
        print("Usage: pvm <bytecode.json>")
        sys.exit(1)

    with open(sys.argv[1],'r') as f:
        new = (f.read()
		.replace('#!/usr/bin/pvm\n','')
		.replace('#!/usr/bin/env pvm\n',''))
#        print(new)
        bytecode = json.loads(new)
    vm = VM()
    vm.load(bytecode)
    vm.run()
